version: '3'
services:
  db_host:
    container_name: mysqldb
    image: mysql
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
networks:
  net: